### ISSUE TITLE
Upload images to S3 or Google Cloud

### ISSUE THREAD

**Issue by sohai9** [sohai9/Project-2#9]
1. Find a way to upload images to S3 or Google Cloud
2. Packages has been imported in the server.js file.
3. You can use or introduce any new package
4. Please create a file called upload-photos.hbs under views & upload-photos.js under public/javascruipt/upload-photos.js

**Comment by kathryndunphy** [comment]
Please see #3 
There is an open issue on this topic and should be added there

**Comment by kathryndunphy** [comment]
I've added your response the original issue and am closing this one.
